# Generated by Django 5.2.14 on 2026-05-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fd',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='fd',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_left', models.IntegerField()),
                ('sent_on', models.DateField(auto_now_add=True)),
                ('fd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdapp.fd')),
            ],
        ),
    ]
