# Generated by Django 5.2.1 on 2026-05-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdapp', '0003_fd_user_delete_reminderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd',
            name='reminder_0_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fd',
            name='reminder_15_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fd',
            name='reminder_1_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fd',
            name='reminder_30_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fd',
            name='reminder_7_sent',
            field=models.BooleanField(default=False),
        ),
    ]
